[categories]
arguments = { source_path = "arguments", target_path = "arguments" }
commands = { source_path = "commands", target_path = "commands" }
interaction-handlers = { source_path = "interaction-handlers", target_path = "interaction-handlers" }
listeners = { source_path = "listeners", target_path = "listeners" }
preconditions = { source_path = "preconditions", target_path = "preconditions" }
routes = { source_path = "routes", target_path = "routes" }

[templates.arguments]
argument = { aliases = ["a", "arg"] }

[templates.commands]
context-menu-command = { aliases = ["cmc", "context", "contextmenu", "contextmenucommand"] }
message-command = { aliases = ["mc", "message", "messagecommand"] }
slash-command = { aliases = ["sc", "command", "slash", "slashcommand"] }

[templates.interaction-handlers]
autocomplete-interaction-handler = { aliases = ["aih", "auto", "autocomplete"] }
button-interaction-handler = { aliases = ["bih", "button"] }
modal-interaction-handler = { aliases = ["mih", "modal"] }
select-menu-interaction-handler = { aliases = ["smih", "select"] }

[templates.listeners]
listener = { aliases = ["l"] }

[templates.preconditions]
precondition = { aliases = ["p"] }

[templates.routes]
route = { aliases = ["r"] }
