[categories]
arguments = { path = "arguments" }
commands = { path = "commands" }
interaction_handlers = { path = "interaction-handlers" }
listeners = { path = "listeners" }
preconditions = { path = "preconditions" }
routes = { path = "routes" }

[templates.arguments]
argument = { aliases = ["a", "arg"] }

[templates.commands]
contextmenucommand = { aliases = ["cmc", "context"] }
messagecommand = { aliases = ["mc", "message"] }
slashcommand = { aliases = ["sc", "command"] }

[templates.interaction_handlers]
autocompleteinteractionhandler = { aliases = ["aih", "autocomplete"] }
buttoninteractionhandler = { aliases = ["bih", "button"] }
modalinteractionhandler = { aliases = ["mih", "modal"] }
selectmenuinteractionhandler = { aliases = ["smih", "select"] }

[templates.listeners]
listener = { aliases = ["l"] }

[templates.preconditions]
precondition = { aliases = ["p"] }

[templates.routes]
route = { aliases = ["r"] }
